In [83]:
import pandas as pd
df = pd.read_excel('/Users/macbook/Downloads/Training_1/Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [84]:
df = df.drop(columns=['Not_Useful_Column'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [85]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [86]:
# Cleaning Last Name Column
# df['Last_Name'] = df['Last_Name'].str.strip()
# df['Last_Name'] = df['Last_Name'].str.lstrip('/')
# df['Last_Name'] = df['Last_Name'].str.lstrip('...')
# df['Last_Name']
df['Last_Name'] = df['Last_Name'].str.strip('. /')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [87]:
# Manipulating the Phone Number and appplying data formatting
# df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
# df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]', '', regex=True)
# df['Phone_Number'] = df['Phone_Number'].str.replace('nan', '')
# df['Phone_Number'] = df['Phone_Number'].str.replace('Na', '')
# df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:9])
# df['Phone_Number'] = df['Phone_Number'].str.replace('--', '')
# df['Phone_Number']

# Tidy Method
df['Phone_Number'] = df['Phone_Number'].fillna('')
df['Phone_Number'] = (df['Phone_Number'].astype(str).str.replace('[^0-9]', '', regex=True))   # strip everything except digits in one go
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10] if len(x) == 10 else x)
df['Phone_Number'].unique()

<StringArray>
['123-545-5421', '123-643-9775', '706-695-0392', '123-543-2345',
 '876-678-3469', '304-762-2467',             '']
Length: 7, dtype: str

In [88]:
# Separate the Address
df[['Street', 'City', 'Postal_Code']] = df['Address'].str.split(',', n = 2, expand = True)
df = df.drop(columns=['Address'])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,NaN,NaN
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,No,No,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN

In [89]:
# Replace Yes and No with Y and N correspondingly
df['Paying Customer'] = df['Paying Customer'].apply(lambda x: "Y" if x in ['Yes', 'Y'] 
                                                    else ("N" if x in['No', 'N'] else x))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Y,No,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,N,Yes,93 West Main Street,NaN,NaN
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Y,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,N,No,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Y,No,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Y,No,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Y,No,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Y,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [90]:
# Replace Yes and No with Y and N
df['Do_Not_Contact'] = df['Do_Not_Contact'].apply(lambda x: 'Y' if x in ['Yes', 'Y'] 
                                                else('N' if x in ['No', 'N'] else x))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,706-695-0392,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,N,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [91]:
# Remove empty phone numbers
df = df[df['Phone_Number'] != '']
# Remove rows with Do not Contact Y
df = df[df['Do_Not_Contact'] == 'N']
# Reset index count

df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City,Postal_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
6,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,NaN,NaN
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [92]:
# Filling Nan values with meaningufl data
df['City'] = df['City'].fillna('Unknown')
# Drop the Postal Code because each row is almost empty
df = df.drop(columns=['Postal_Code'])
# Display First 10 values
df.head(10)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,City
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,Unknown
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,Unknown
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,Unknown
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,Unknown
6,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,Unknown
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,Unknown
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine

In [93]:
df.info()
df.shape
print(f"This data set has a total of {df.shape[0]} rows and {df.shape[1]} columns")

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10 non-null     int64
 1   First_Name       10 non-null     str
 2   Last_Name        10 non-null     str
 3   Phone_Number     10 non-null     str
 4   Paying Customer  10 non-null     str
 5   Do_Not_Contact   10 non-null     str
 6   Street           10 non-null     str
 7   City             10 non-null     str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes
This data set has a total of 10 rows and 8 columns